/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.kototuz.file_receiver;

public final class R {
    public static final class attr {
    }
    public static final class font {
        public static final int jetbrains_mono=0x7f020000;
    }
    public static final class id {
        public static final int state_text=0x7f040000;
    }
    public static final class layout {
        public static final int simple_layout=0x7f030000;
    }
}
